import Head from 'next/head';
import { useCallback, useState, MouseEvent } from 'react';
import { UserList, User } from '../components';

export default function Home() {
  const [userId, setUserId] = useState<number>();

  const handleClick = useCallback(async (e: MouseEvent) => {
    if (e.target instanceof HTMLElement) {
      const userId = e.target.dataset['userid'];

      userId && setUserId(Number(userId));
    }
  }, []);

  return (
    <>
      <Head>
        <title>Axios Interceptor Customizing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <h1>Axios Interceptor Customizing</h1>
        <UserList onClick={handleClick} />
        {userId && <User userId={userId} />}
      </main>
    </>
  );
}
