import Head from 'next/head';
import UserList from '../components/UserList';

export default function Home() {
  return (
    <>
      <Head>
        <title>Axios Interceptor Customizing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <h1>Axios Interceptor Customizing</h1>
        <UserList />
      </main>
    </>
  );
}
