import Head from 'next/head';
import { UserList } from '@components/index';

export default function Home() {
  return (
    <>
      <Head>
        <title>Error Boundary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <h1>Init Project</h1>
        <UserList />
      </main>
    </>
  );
}
